### ISSUE TITLE
Visdom visualization for text

### ISSUE THREAD

**Issue by shubhamagarwal92** [woozzu/tagan#10]
Hi, 

Thanks for providing the code. 

I was actually trying out some of the visualization using visdom library. Pretty cool! But that shows only the input and generated image with no actual text input. I am planning to extend for text as well. So need some pointers and directions. 

- Why do you multiply and add the original images by 0.5 [here](https://github.com/woozzu/tagan/blob/master/train.py#L195) for visualization? 
- If I want to also display the text here; how should I go ahead?

```
text_vis = txt.cpu().detach().numpy()
vis.text(text_vis, nrow=4, opts=dict(title='input text'))
```
However, how do I get the actual text from the tensor? Could you point me to the relevant function please or how do I get the vocab?

**Comment by woozzu** [comment]
@shubhamagarwal92 As the tensors are in the range of [-1, 1), we need to do so to adjust the range to [0, 1). For text visualization, one option is to modify `data.py` so that you get raw texts in the for loop of the main script. Please refer to [here](https://github.com/woozzu/tagan/blob/master/data.py#L100) for raw text.
